spring:
  datasource:
    url: jdbc:postgresql://${POLICY_DB_HOST:100.114.133.69}:${POLICY_DB_PORT:30432}/claimassist_policy_local
    username: ${POLICY_DB_USER:claimassist}
    password: ${POLICY_DB_PASSWORD:claimassist}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://100.114.133.69:30080/realms/claimassist-dev}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://100.114.133.69:30080/realms/claimassist-dev/protocol/openid-connect/certs}

server:
  port: 8084

security:
  internal:
    trusted-service-client-ids: ${TRUSTED_SERVICE_CLIENT_IDS:claimassist-admin-service,claims-service,agent-service}

policy:
  migration:
    legacy-coverage-plan-map: {}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  metrics:
    enable:
      jvm: true
      process: true
      logback: true

    distribution:
      percentiles-histogram:
        http.server.requests: true

    tags:
      application: ${spring.application.name}
      environment: local-k8s
      source: intellij
      developer: ${CLAIMASSIST_DEVELOPER_NAME:unknown}

  prometheus:
    metrics:
      export:
        enabled: true

  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

tracing:
  sampling:
    probability: 1.0

zipkin:
  tracing:
    endpoint: ${ZIPKIN_ENDPOINT:http://100.114.133.69:30941/api/v2/spans}

logging:
  level:
    com.claimassist: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
