spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/claimassist_customer_local
    username: ${POSTGRES_USER:claimassist}
    password: ${POSTGRES_PASSWORD:claimassist}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2s
      lettuce:
        pool:
          max-active: 32
          max-idle: 16
          min-idle: 4

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 2147483647
      batch-size: 16384
      linger-ms: 10
      compression-type: snappy
      delivery-timeout-ms: 120000
      properties:
        linger.ms: 10
        request.timeout.ms: 30000
        retry.backoff.ms: 1000
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: customer-service-local

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/claimassist}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8180/realms/claimassist/protocol/openid-connect/certs}

      client:
        registration:
          internal-service:
            provider: keycloak
            client-id: ${SERVICE_CLIENT_ID:claimassist-admin-service}
            client-secret: ${SERVICE_CLIENT_SECRET:local-dev-admin-client-secret}
            authorization-grant-type: client_credentials

        provider:
          keycloak:
            token-uri: ${SERVICE_TOKEN_URI:http://localhost:8180/realms/claimassist/protocol/openid-connect/token}



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.claimassist: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
