spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service
              uri: http://example
              predicates:
                - Path=/customer/**

