apiVersion: v1
kind: ConfigMap
metadata:
  name: claimassist-shared-config
  namespace: claimassist-core
data:
  POSTGRES_USER: claimassist
  POSTGRES_PASSWORD: claimassist
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  EUREKA_SERVER_URL: http://discovery-service:8761/eureka
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/claimassist
  KEYCLOAK_JWKS_URI: http://keycloak:8080/realms/claimassist/protocol/openid-connect/certs
  SPRING_PROFILES_ACTIVE: k8s
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: claimassist-core
type: Opaque
stringData:
  SERVICE_CLIENT_SECRET: ${SERVICE_CLIENT_SECRET}
  KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
  INTERNAL_API_SECRET: ${INTERNAL_API_SECRET}
  GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
