server:
  port: 8761
  compression:
    enabled: true

eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  tracing:
    sampling:
      probability: 0.1
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

