server:
  port: 8761

eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 0.5

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

