apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SERVICE_CLIENT_SECRET: "{{ .Values.serviceClientSecret | default "changeme" }}"
  KEYCLOAK_ADMIN_CLIENT_SECRET: "{{ .Values.keycloakAdminClientSecret | default "changeme" }}"
  INTERNAL_API_SECRET: "{{ .Values.internalApiSecret | default "changeme" }}"
  GRAFANA_ADMIN_PASSWORD: "{{ .Values.grafana.admin.password | default "changeme" }}"

