spring:
  application:
    name: config-service

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:file:///D:/Mayur/1/Deployment/insurance-ai-platform/local-config-repo}
          default-label: ${CONFIG_GIT_LABEL:main}
          clone-on-start: true

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  health:
    config:
      enabled: false

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

---
spring:
  config:
    activate:
      on-profile: k8s

  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false