---
# Source: claimassist/templates/keycloak-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: claimassist-keycloak-admin
  namespace: "default"
  labels:
    app.kubernetes.io/name: "claimassist"
    app.kubernetes.io/instance: "claimassist"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: "claimassist"
    app.kubernetes.io/managed-by: "Helm"
    environment: "dev"
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "Y7mhTktHwMI54YVrFg63PH0M3jcEwyfh"
  KEYCLOAK_ADMIN_CLIENT_ID: "claimassist-admin-service"
  KEYCLOAK_ADMIN_CLIENT_SECRET: "z9FtBiAKMiDe76EudUoOA43cXXMmUSeq"

